### ISSUE TITLE
Questions for the outcomes in the inductive load circumstance.

### ISSUE THREAD

**Issue by ypymy** [IhabMohamed/MPC-3-Phase-Inverters#1]
Hello, thank you first for your impressive research. However, in the case of inductive load, a series load of resistance and inductance（RL）is used. The voltage cannot track the expected amplitude, and the three-phase voltages （v_a, b, and c）present different amplitudes, where R=100ohms, L=0.01H. 

After carefully reading your paper titled 'A Neural-Network-Based Model Predictive Control of Three-Phase Inverter With an Output LC Filter', in figure 14, you show that the amplitude of three-phase voltage can be tracked under the MPC control for an inductive load.

Excuse me, is there something wrong with me? Under the linear load and RC load, the simulation results are consistent with the description in your article. Why it is not done well for inductive load, that's always been bothering me

P.S. The simulation model comes from this project,  thanks again.

Sincerely hope to receive your reply.

**Comment by IhabMohamed** [comment]
Hi @ypymy, sorry for the delayed response, and many thanks for your message. Indeed, I just run the simulation with RL load (for, R=100, L=0.01), and it works very well for me. I do not know what is going wrong on your side. However, as you know, the performance of MPC mainly based on the sampling time, filter inductance, filter capacitance, predefined cost function, etc.  

For ANN-MPC, in figure 14, we tried to prove that the trained ANN can work with loads that have not been used/seen during the training phase. This is not surprising because the ANN learns the mathematical model of the system to be controlled and its dynamics.

**Comment by ypymy** [comment]
Thank you for your reply, the simulation model work well now by adjusting the RLC parameters, and now I am doing some further attempts.

Regards,
KimYi Yu

**Comment by ypymy** [comment]
> Hi @ypymy, sorry for the delayed response, and many thanks for your message. Indeed, I just run the simulation with RL load (for, R=100, L=0.01), and it works very well for me. I do not know what is going wrong on your side. However, as you know, the performance of MPC mainly based on the sampling time, filter inductance, filter capacitance, predefined cost function, etc.
> 
> For ANN-MPC, in figure 14, we tried to prove that the trained ANN can work with loads that have not been used/seen during the training phase. This is not surprising because the ANN learns the mathematical model of the system to be controlled and its dynamics.

**Comment by IhabMohamed** [comment]
Hi @ypymy, I am so happy to hear that :-) 
All the best!

Regards,
Ihab
